name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Cache Dependencies
        run: deno cache deps.ts
      - name: Run tests
        run: deno test --no-check -A --location http://127.0.1 --unstable --coverage=coverage ./tests -q
      - name: Create coverage report
        run: deno --unstable coverage ./coverage --lcov > coverage.lcov
      - name: Collect coverage
        uses: codecov/codecov-action@v1.5.0
        with:
          file: ./coverage.lcov
